version: '3.9'

services:
  api1:
    image: rinha #TODO: upload image in docker hub
    build: .
    hostname: api1
    environment:
      - DB_HOST=db
      - DB_USER=feijuca
      - DB_PASSWORD=feijuca
      - DB_NAME=rinha
      - DB_PORT=5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 5000
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '80MB'
    networks:
      internal-network:

  api2:
    image: rinha # TODO: upload image in docker hub
    build: .
    hostname: api2
    environment:
      - DB_HOST=db
      - DB_USER=feijuca
      - DB_PASSWORD=feijuca
      - DB_NAME=rinha
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 5000
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '80MB'
    networks:
      internal-network:

  nginx:
    image: nginx:latest
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      outside:
      internal-network:

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=feijuca
      - POSTGRES_USER=feijuca
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.56'
          memory: '340MB'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U feijuca -d rinha'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      internal-network:
      outside:
networks:
  internal-network:
    internal: true
    driver: bridge
  outside:
    driver: bridge